name: qs_purchase
description: QS Library for Flutter purchase
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  qs_blocs:
    git: https://github.com/artsiombarouski/qs_blocs.git
  qonversion_flutter: ^4.3.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0