name: qs_purchase
description: QS Library for Flutter purchase
version: 0.1.2
homepage: https://github.com/artsiombarouski/qs_purchase.git
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  qs_blocs:
    git:
      url: https://github.com/artsiombarouski/qs_blocs.git
      ref: main
  qonversion_flutter: ^7.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1